### ISSUE TITLE
TV.py (Book version) channelUp method

### ISSUE THREAD

**Issue by Steve-Arch** [IrvKalb/Object-Oriented-Python-Code#11]
Hey Irv,

Apologies if this isn't the right medium for this! (Really enjoying the book by the way!)

In the book version of TV.py (Page 37) there seems to be an error in the channelUp method. Specifically at line 38. 
The book has the following IF statement:
```
        if self.channelIndex > self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel
```

This produces an `IndexError` if you increment the `channelIndex` variable too many times and then call the `showInfo` method.

I can see in the online resources via [nostarch](https://nostarch.com/object-oriented-python) that this has been fixed with the IF statement looking like this:

```
        if self.channelIndex == self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel
```

I'm just wondering if you were aware of this?

Thanks, Stephen.

**Comment by IrvKalb** [comment]
Hello Stephen,

Thanks for your message - it's always great to hear directly from readers.

You are correct about this error.  As you pointed out, in that line, the code has already been changed from a greater than to an equals equals to correct that error.
Whenever a reader finds an error, I update the code and the change gets put into the next printing of the book.  Can you let me know what printing of the book you have?  This can be found near the top of the second printed page under the Copyright notice.

Also, I maintain the "errata" page for the book, but I don't see this change listed there.  I'll have to add it.  Can you also tell me where you saw the corrected code?  Was it in the code on my GitHub page?

I'm very glad to hear that you are enjoying the book so far.  I hope that you will enjoy it even more when you get into it farther.

Thanks,

Irv

On Dec 10, 2024, at 7:39 AM, Stephen ***@***.***> wrote:



Hey Irv,

Apologies if this isn't the right medium for this! (Really enjoying the book by the way!)

In the book version of TV.py (Page 37) there seems to be an error in the channelUp method. Specifically at line 38.
The book has the following IF statement:

        if self.channelIndex > self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel


This produces an IndexError if you increment the channelIndex variable too many times and then call the showInfo method.

I can see in the online resources via nostarch<https://nostarch.com/object-oriented-python> that this has been fixed with the IF statement looking like this:

        if self.channelIndex == self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel


I'm just wondering if you were aware of this?

Thanks, Stephen.

**Comment by IrvKalb** [comment]
PS:  The book is about to go into its fourth printing!

On Dec 10, 2024, at 7:39 AM, Stephen ***@***.***> wrote:



Hey Irv,

Apologies if this isn't the right medium for this! (Really enjoying the book by the way!)

In the book version of TV.py (Page 37) there seems to be an error in the channelUp method. Specifically at line 38.
The book has the following IF statement:

        if self.channelIndex > self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel


This produces an IndexError if you increment the channelIndex variable too many times and then call the showInfo method.

I can see in the online resources via nostarch<https://nostarch.com/object-oriented-python> that this has been fixed with the IF statement looking like this:

        if self.channelIndex == self.nChannels:
            self.channelIndex = 0  # wrap around to the first channel


I'm just wondering if you were aware of this?

Thanks, Stephen.

**Comment by Steve-Arch** [comment]
Hey Irv!

Thank you for responding!

>Can you let me know what printing of the book you have? 

It's a "Third Printing" according to the second page.
It was purchased for me by my employer from Amazon UK, if that helps?

>Can you also tell me where you saw the corrected code?  Was it in the code on my GitHub page?

Sure, I found the corrected code first on No Starch's website here: https://nostarch.com/download/Object-Oriented-Python-Code.zip

I also found the same code in your GIT repo here: https://github.com/IrvKalb/Object-Oriented-Python-Code/blob/master/Chapter_2/TV.py

The contents in your GIT repo and the .ZIP from No Starch seem to match up according to this diff tool: https://www.diffchecker.com/3YUD0Bxu/

Your repo is on the left, and the .ZIP contents on the right.

I'd imagine most people haven't ran into the bug as it only occurs if you increment the `channelIndex` variable to 11, and then call the `showInfo` method. Beyond this  `channelIndex` wraps back around to index 0, and before 11 is a valid index. So maybe I'm just being picky, but I thought it was worth mentioning anyway :smile: 

Stephen.

**Comment by IrvKalb** [comment]
Hi Stephen,

Thanks for your answers.

So the good news is that the correct code is available for downloading.  The bad news is that it appears that, while I did correct the code, that code hasn't made it into the book.  I will contact the publisher and see if it possible to make this correction before the 4th printing is completed.

I have also added this to the list of errata here:  http://www.furrypants.com/ObjectOrientedPython-Errata/

Thanks very much for letting me know about this.

And please feel free to contact me with any other updates or questionable code that you may find.

Irv

On Dec 10, 2024, at 11:22 AM, Stephen ***@***.***> wrote:



Hey Irv!

Thank you for responding!

Can you let me know what printing of the book you have?

It's a "Third Printing" according to the second page.
It was purchased for me by my employer from Amazon UK, if that helps?

Can you also tell me where you saw the corrected code? Was it in the code on my GitHub page?

Sure, I found the corrected code first on No Starch's website here: https://nostarch.com/download/Object-Oriented-Python-Code.zip

I also found the same code in your GIT repo here: https://github.com/IrvKalb/Object-Oriented-Python-Code/blob/master/Chapter_2/TV.py

The contents in your GIT repo and the .ZIP from No Starch seem to match up according to this diff tool: https://www.diffchecker.com/3YUD0Bxu/

Your repo is on the left, and the .ZIP contents on the right.

I'd imagine most people haven't ran into the bug as it only occurs if you increment the channelIndex variable to 11, and then call the showInfo method. Beyond this channelIndex wraps back around to index 0, and before 11 is a valid index. So maybe I'm just being picky, but I thought it was worth mentioning anyway 😄

Stephen.

**Comment by Steve-Arch** [comment]
Hey Irv,

No worries at all.

I'll get this issue closed off.

Thanks for your help.

Stephen.

**Comment by IrvKalb** [comment]
Glad to hear the issue is resolved.

I hope you enjoy the rest of the book.

Irv
