### ISSUE TITLE
get cards from the top or bottom of decks

### ISSUE THREAD

**Issue by rmbhub** [IrvKalb/Object-Oriented-Python-Code#8]
hi,  Thank you for the wonderful python object-oriented book.
But I was a little confused when I tried to practice the code in chapter 1.

We always take cards from the top, not the bottom,  Is it better to use **pop(0)** in code?
when the code run **pop()**,  the pointer is always placed in the last position, The next card will always be **NULL**;
If i take a card from the top with **pop(0)**, next is the top card, as described in the original book.

**Comment by IrvKalb** [comment]
Hi,

Thanks for your comment - and I'm glad that you are enjoying the book.

I assume that you are referring to the getCard(deckListIn) function which is called to retrieve a card.  In Python, list.pop() with no arguments removes the last element from the list and returns it.  In each call to getCard(), the the call to deckListIn.pop() removes the last card, the list shrinks by one element, and returns the card that was popped.  That way, each time getCard() is called,  pop() always gets the last card in the list, no matter how long the list is.  There is no "pointer" involved, and the next card will never be NULL.  

Yes, the code could have used pop(0) and that would have worked as well.  Since the whole deck is randomized before any call to getCard(), it really doesn't matter.

Hope that helps.

Irv
